name: CI
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quick repo smoke test
        run: |
          echo "Checked out repo. Add your CI checks here (lint, tests, build)."
